## nav
navbar:
  visiable: auto
  logo: 
    img: '' # volantis-static/media/org.volantis/blog/Logo-NavBar@3x.png
    icon:
    title: 'Nano' 
  menu:
    - name: 博客
      icon: fa-solid fa-rss
      url: /
    - name: 分类
      icon: fa-solid fa-folder-open
      url: categories/
    - name: 标签
      icon: fa-solid fa-tags
      url: tags/
    - name: 归档
      icon: fa-solid fa-archive
      url: archives/
    - name: 友链
      icon: fa-solid fa-link
      url: friends/
    - name: 关于
      icon: fa-solid fa-info-circle
      url: about/
## cover
cover:
  height_scheme: full # full, half
  layout_scheme: search # blank (留白), search (搜索), dock (坞), featured (精选), focus (焦点)
  title: 'Mlikiowa Home Village'
  subtitle: ''
  background: https://s2.loli.net/2022/08/09/NXMISrakx8UmdfC.jpg
  search: A Wonderful Theme for Hexo # search
  features:
    - name: 博客
      img: volantis-static/media/twemoji/assets/svg/1f4f0.svg
      url: /
    - name: 文档
      img: volantis-static/media/twemoji/assets/svg/1f516.svg
      url: /v5/getting-started/
      target: _self
    - name: 示例
      img: volantis-static/media/twemoji/assets/svg/1f4af.svg
      url: /examples/
    - name: 帮助
      img: volantis-static/media/twemoji/assets/svg/1f4ac.svg
      url: /faqs/
    - name: 鸣谢
      img: volantis-static/media/twemoji/assets/svg/1f497.svg
      url: /contributors/
    - name: 归档
      img: volantis-static/media/twemoji/assets/svg/1f5c3.svg
      url: /archives/    
## comments
comments:
  service: giscus
  giscus:
    repo: Mlikiowa/MliKiowa.github.io
    repo-id: R_kgDOHxvLiA
    category: General
    category-id: DIC_kwDOHxvLiM4CQr9N
    mapping: "url"
    reactions-enabled: "1"
    emit-metadata: "0"
    lang: "zh-CN"
    theme:
      light: "light" # https://fastly.jsdelivr.net/gh/volantis-x/cdn-volantis@master/css/giscus/light.css
      dark: "dark" # https://fastly.jsdelivr.net/gh/volantis-x/cdn-volantis@master/css/giscus/dark.css
## Friend
pages:
  friends:
    layout_scheme: traditional # simple: 简单布局, traditional: 传统布局
## article
article:
  preview:
    scheme: landscape # landscape  
    pin_icon: https://fastly.jsdelivr.net/gh/twitter/twemoji@13.0/assets/svg/1f4cc.svg
    # auto generate title if not exist
    auto_title: true # false, true
    # auto generate excerpt if not exist
    auto_excerpt: true # false, true
    # show split line or not
    line_style: solid # hidden, solid, dashed, dotted
    # show readmore button
    readmore: auto # auto, always
  # 文章详情页面的文章卡片本体布局方案
  body:
    top_meta: [author, category, date, wordcount] #启用评论数量需在此添加       
    bottom_meta: [updated, tags]
    footer_widget:
      copyright:
        enable: true     
        content:
          - 'Abide by  CC BY-NC-SA 4.0'                
    meta_library:   
      author:
        avatar: https://q1.qlogo.cn/g?b=qq&nk=1627126029&s=100
        name: Mlikiowa
        url: /
      date:
        icon: fas fa-calendar-alt
        title: '发布于：'
        format: 'll' # 日期格式 http://momentjs.com/docs/
      category:
        icon: fas fa-folder-open      
      # 文章字数和阅读时长
      wordcount:
        icon_wordcount: fas fa-keyboard
        icon_duration: fas fa-hourglass-half
      # 文章标签
      tags:
        icon: fas fa-hashtag  
site_footer:
  layout: [copyright]
  copyright: '⌘ Hexo With Volantis'  
custom_css:
  cursor:
    enable: true
  font_smoothing: true
blogger:
  class: blogger
  display: [desktop, mobile]
  avatar: http://q1.qlogo.cn/g?b=qq&nk=1627126029&s=100
  title: Mlikiowa
  subtitle:
  jinrishici: true # Poetry Today. You can set a string, and it will be displayed when loading fails.
  social: true
## sidebar
sidebar:
  position: right # left right
  # 主页、分类、归档等独立页面
  for_page: [blogger, category]
  for_post: [toc]
  widget_library:
    # ---------------------------------------
    # blogger info widget
    blogger:
      class: blogger
      display: [desktop, mobile] # [desktop, mobile]
      avatar: https://q1.qlogo.cn/g?b=qq&nk=1627126029&s=100
      shape: rectangle # circle, rectangle
      url: /about/
      title:
      subtitle:
      jinrishici: true # Poetry Today. You can set a string, and it will be displayed when loading fails.
      social:
        - icon: fa-solid fa-rss
          url: /atom.xml
        - icon: fa-solid fa-envelope
          url: mailto:me@xxx.com
        - icon: fab fa-github
          url: https://github.com/volantis-x/
        - icon: fa-solid fa-headphones-alt
          url: /
    # ---------------------------------------
    # toc widget (valid only in articles)
    toc:
      class: toc
      display: [desktop, mobile] # [desktop, mobile]
      sticky: true
      header:
        icon: fa-solid fa-list
        title: 本文目录
      list_number: false
      min_depth: 2
      max_depth: 5
    category:
      class: category
      display: [desktop] # [desktop, mobile]
      header:
        icon: fa-solid fa-folder-open
        title: 文章分类
        url: /blog/categories/
    webinfo:
      class: webinfo
      display: [desktop]
      header:
        icon: fa-solid fa-award
        title: 站点信息
      type:
        article:
          enable: true
          text: '文章数目：'
          unit: '篇'
        runtime:
          enable: false
          data: '2020/01/01'    # 填写建站日期
          text: '已运行时间：'
          unit: '天'
        wordcount:
          enable: false
          text: '本站总字数：'   # 需要启用 wordcount
          unit: '字'
        visitcounter:
          siteuv:
            enable: false
            text: '本站访客数：'
            unit: '人'
          sitepv:
            enable: false
            text: '本站总访问量：'
            unit: '次'
        lastupd:
          enable: true
          friendlyShow: true    # 更友好的时间显示
          text: '最后活动时间：'
          unit: '日'
    # ---------------------------------------
    # lastupdate widget
    lastupdate:
      class: lastupdate
      display: [desktop, mobile]
      header:
        icon: fa-solid fa-clock WISTERIA
        title: 最近更新
plugins:
  wordcount:
    enable: true
